name: Ruby Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/my_bot_ruby-ci:latest
    permissions:
      packages: read
    name: Ruby 3.4.6
    
    steps:
    - uses: actions/checkout@v3
    - name: Install gems
      run: bundle install --jobs 4 --retry 3
    - name: Setup test environment
      run: |
        mkdir -p tmp/
        touch .env
        echo "BROWSER_PATH=/usr/bin/chromium-browser" >> .env
        echo "TOKEN=test_token" >> .env
        echo "CHAT_ID=123456789" >> .env
    - name: Run tests
      run: bundle exec rspec
    - name: Run Rubocop
      run: bundle exec rubocop || true
    - name: Build gem
      run: bundle exec rake build