name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set environment to test
        run: echo "RAILS_ENV=test" >> $GITHUB_ENV

      - name: Set up Ruby 3.3.4
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: 3.3.4
            bundler-cache: true

      - name: Install dependencies
        run: make install

      - name: Run Rubocop
        run: make lint
        continue-on-error: true

      - name: Run rspec
        run: make tests
