name: Daily Send

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/my_bot_ruby-ci:latest
    name: Send daily message
    concurrency:
      group: daily-send
      cancel-in-progress: false
    env:
      TOKEN: ${{ secrets.TOKEN }}
      ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
      APP_ENV: production
      BROWSER_PATH: /usr/bin/chromium-browser
      BUNDLE_BUILD__NOKOGIRI: "--use-system-libraries"
    steps:
      - name: Checkout (with submodules via PAT)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PRIVATE_REPOS_TOKEN }}
          persist-credentials: false

      - name: Fix git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Add container platform to lockfile
        run: bundle lock --add-platform x86_64-linux-musl

      - name: Bundle install
        run: bundle install --jobs 4 --retry 3 --quiet

      - name: Run sender
        run: make start