name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby 3.1.3
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: 3.1.3
            bundler-cache: true

      - name: Install dependencies
        run: make install

      - name: Run Rubocop
        run: make lint

      - name: Run rspec
        run: make tests
